### ISSUE TITLE
Sometimes a player doesnt get their dests initialized in the beginning of the game and is unable to make a move

### ISSUE THREAD

**Issue by nnickoloff1234** [gbtami/pychess-variants#1499]
* Sometimes a player doesnt get their dests initialized in the beginning of the game and is unable to make any move.
* Not clear what conditions cause this - happened to me once and another player reported in chat something that sounded like the same problem. 
* Maybe try reproducing it by inducing disconnect+reconnect before first move or while game starts or before it receives the first init board message.
* Refreshing the browser page fixes the problem

**Comment by gbtami** [comment]
This should be fixed after https://github.com/gbtami/pychess-variants/commit/a7e491bd0b8062a66112f2fd30509c7c0f2ecd29
Feel free to reopen if it occurs again.

**Comment by nnickoloff1234** [comment]
still happens sometimes, cant quite understand when.

**Comment by nnickoloff1234** [comment]
actually i now realized yesterday when i was testing i hadnt yet pulled last changes from git, which might be the reason i was still getting this bug, but not sure. i will keep it open a while longer in case i notice it again.

**Comment by nnickoloff1234** [comment]
didnt experience it not a single time today while testing other stuff, closing it again
