### ISSUE TITLE
During premove, king appears to be able to capture to the Rook's location when castling is available

### ISSUE THREAD

**Issue by PLMMJ-FH** [gbtami/pychess-variants#1686]
When premoving, the King looks to be able to capture the Rook's location. However, selecting this premove does nothing.
![King Rook Capture](https://github.com/user-attachments/assets/d38020c5-927f-4b10-8ccf-bfd9860e9608)

This also occurs in Shatranj (I was going to put this in #1684 until discovering it happens in chess too):
![Shatranj King Castling Thing](https://github.com/user-attachments/assets/54e97298-b5d4-4fd1-929e-226ff6d6e9d5)

I have no idea what is going on here but it seems too obvious to be a bug.

**Comment by gbtami** [comment]
This was already fixed via https://github.com/gbtami/pychess-variants/commit/ba285a4fbb418e3623c02f8d0fc0d965188fc7b2 but it was not deployed yet.

**Comment by PLMMJ-FH** [comment]
![Ahem it still happens](https://github.com/user-attachments/assets/75c888ed-de54-45e5-bcd1-16bb6415001c)
You seem to have only fixed it for Shatranj, it is still a thing in S-Chess at least

**Comment by PLMMJ-FH** [comment]
Duck Chess is even worse. For some reason, the King still appears to be able to capture the kingside rook despite it obviously not being unmoved.

![Ducks Even Worse](https://github.com/user-attachments/assets/995797e3-ab50-48fa-ad1e-fe5dcebe2b67)

**Comment by gbtami** [comment]
This is by design. Premove targets are NOT just valid move targets only.
They are created from piece movements without checking all if the the game rules. The is because opponent next move can change which our next move will be possible or not possible.
Look at this screenshot I created on lichess ![https://i.imgur.com/WgYOUaO.png](https://i.imgur.com/WgYOUaO.png)
